# Generated by Django 3.1.3 on 2021-06-08 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='my_sub_channels',
            field=models.ManyToManyField(blank=True, related_name='my_sub_channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channel',
            name='subs',
            field=models.ManyToManyField(blank=True, related_name='subs', to=settings.AUTH_USER_MODEL),
        ),
    ]
